#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/alpine-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

src=rsync://mirrors.tuna.tsinghua.edu.cn/alpine/
dest=/data/alpine/

# uncomment this to exclude old v2.x branches
exclude="--exclude v2.* --exclude edge*"

echo "Starting..."

/usr/bin/rsync \
        -v \
        --progress \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --delay-updates \
        --timeout=600 \
        $exclude \
        "$src" "$dest"

echo "Done."