#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/ubuntu-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

src=rsync://archive.ubuntu.com/ubuntu
dest=/data/ubuntu/

exclude="--exclude zesty* --exclude oracular* --exclude yakkety* --exclude xenial* --exclude trusty* --exclude mantic* --exclude lunar* --exclude kinetic* --exclude hirsute* --exclude hirsute* --exclude devel*"

echo "Starting..."

mkdir -p "$dest"
/usr/bin/rsync \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --delay-updates \
        --timeout=600 \
        $exclude \
        "$src" "$dest"